#!/sbin/busybox sh

cd /
/sbin/busybox mount -t proc proc /proc
/sbin/busybox mount -t sysfs sysfs /sys

/sbin/busybox mkdir -p /dev/block
/sbin/busybox mknod /dev/block/mmcblk0p9 b 179 9
/sbin/busybox mount -t ext4 /dev/block/mmcblk0p9 /system

if busybox grep -q 1 /sys/class/power_supply/battery/batt_lp_charging ; then
  # low power mode
  /sbin/busybox cp lpm.rc init.rc
  /sbin/busybox rm init.smdk4x12.rc
  exec /sbin/init.sammy
fi

if [ ! -d /system/lib/modules ]; then
	/sbin/busybox mount -o remount,rw /system
	/sbin/busybox mkdir /system/lib/modules
fi;

/sbin/busybox cp -f /lib/modules/* /system/lib/modules

/sbin/busybox umount /system
exec /sbin/init.aosp
